### ISSUE TITLE
Multi-factors Auth doesn't work in environment Node.js 12.x.x

### ISSUE THREAD

**Issue by JUd9in** [valapi/Authentication#2]
Hello! Here's a problem I encountered while using the Multi-factors Authentication Client.

When I run the script in **Node.js 16.x** using the example methods in your API documents like this below.

`await AuthClient.login('BestUsername', 'SuperSecretPassword');`

`if (AuthClient.isMultifactor === true) {
    await AuthClient.verify(SixNum);
}`

In the above situation, I got the proper response containing my access token, entitlements token, etc.

but when I ran the same code in **Node.js 12.x**, the response no longer contained all my account tokens but got an empty cookie like this below.

`
{
  cookie: {
    jar: {
      version: 'tough-cookie@4.1.2',
      storeType: 'MemoryCookieStore',
      rejectPublicSuffixes: true,
      enableLooseMode: false,
      allowSpecialUseDomain: true,
      prefixSecurity: 'silent',
      cookies: [Array]
    },
    ssid: ''
  },
  access_token: '',
  id_token: '',
  expires_in: 3600,
  token_type: 'Bearer',
  session_state: '',
  entitlements_token: '',
  isMultifactor: true,
  isError: false,
  region: { live: 'na', pbe: 'na' },
  createAt: { cookie: 1666426034145, token: 1666426034145 }
}
`

I wonder what contributes to such a difference between the two environments 16.x and 12.x, because the environment of the project I'm currently working on is node.js 12.x.   (sadge

It seems like in 16.x the client would 'remember' the account that the login function logged into, and then send Riot the verification code. But in 12.x, `auth.login()` and `auth.verify()` seem to be two separate functions that don't have a link.

Many Thanks.

**Comment by KTNG-3** [comment]
`http-cookie-agent` are use for multifactor

https://github.com/3846masa/http-cookie-agent/blob/main/package.json#L121
I am always using the latest version of all packages, `http-cookie-agent` are support node >=14

build your package, it open source
I will help you until you close these issues
**:)**

**Comment by JUd9in** [comment]
Thanks, I tried building the package in some old versions of http-cookie-agent supporting Node.js 12, but some features just don't work in old versions of http-cookie-agent (maybe not developed back then). Finally I decided to switch my environment to Node 16 and it works perfectly. Thanks to your help! This package is literally the best i've ever found in GitHub, great work! Thanks!
